### ISSUE TITLE
esy-fswatch in 03 

### ISSUE THREAD

**Issue by idkjs** [EduardoRFS/youtube-channel#10]
How are you using esy-fswatch here ->https://github.com/EduardoRFS/youtube-channel/blob/bbfc3c4aa720d601da784ea7b7bb205575e53567/03-coding-ocaml-on-vscode/hello/esy.json#L17?

I took it out and it seems to work fine.

Thanks.

**Comment by EduardoRFS** [comment]
The goal was to support windows watching but this was not working properly
