### ISSUE TITLE
Esy install isn't working

### ISSUE THREAD

**Issue by d4hines** [EduardoRFS/youtube-channel#9]
When I clone the repo and try running the lambda calculus example I get the following:
```
❯ esy
error: No esy project found (was looking from ~/repos/youtube-channel/07-lambda-calculus-interpreter-in-ocaml and up)
  
esy: exiting due to errors above
```
Ideas?

**Comment by EduardoRFS** [comment]
You should be under the `youtube-channel/07-lambda-calculus-interpreter-in-ocaml/code` folder, also dude, I work with you, you can ask me on Slack

https://github.com/EduardoRFS/youtube-channel/tree/master/07-lambda-calculus-interpreter-in-ocaml/code

**Comment by d4hines** [comment]
Lol. Woops. I didn't notice there was another subdir.

Also, in principle, somebody could have run into the same issue as me, hence I asked via issue (in practice, I doubt anyone else is going to make this mistake 🙄)

**Comment by d4hines** [comment]
Works. Thanks.
